### PR TITLE
License requirements

### PR DESCRIPTION
**Pull request by CR072**

### CODE REVIEW

**Comment by eight2wo** [comment]
@CR072 you definitely don't need that for the "license requirement" -- it's still based on the old license, credits are given to their respective authors in the files mentioned.

**Comment by privt00** [comment]
UwU

**Comment by CR072** [comment]
Copying code is not counted as a "dependency".

**Comment by CR072** [comment]
You should follow what the author of the code says.

**Comment by privt00** [comment]
Am i helpfull?

**Comment by privt00** [comment]
Immagen ading heliactyl to footer

**Comment by eight2wo** [comment]
bro its like forcing someone on something they wouldn't like, you aint forcing anything here, we kindly request you to actually modify the license to state the things in the future, I hope :wink:

**Comment by eight2wo** [comment]
we're just following your license

**Comment by CR072** [comment]
You gotta merge it or face the issues.

**Pull request merged**
